name: SonarCloud Analysis and Code Update

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  sonarqube-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for Gradle Wrapper (Unix)
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Run SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonarqube -Dsonar.projectKey=AvinashNagella1999_user-registraion-api -Dsonar.organization=avinashnagella1999 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.branch.name=master

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install requests openai PyGithub

      - name: Generate and parse SonarCloud report
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: AvinashNagella1999_user-registraion-api
          SONAR_ORGANIZATION: avinashnagella1999
        run: python3 .github/scripts/generateSonarReport.py

      - name: Process issues and update code
        if: steps.generateSonarReport.outputs.has_issues == 'true'
        env:
          OPENAI_API_KEY: ${{ secrets.OPEN_AI_KEY_2 }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python3 .github/scripts/processReportAndUpdateCode.py

      - name: Create Pull Request to release branch
        if: steps.generate_and_parse_sonarcloud_report.outputs.has_issues == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_HEAD_REF: master
        run: python3 .github/scripts/createPR.py
